FROM node:16.15.0 as build

WORKDIR /demo-app
RUN npm install -g @angular/cli
COPY package*.json ./
RUN yarn cache clean && yarn --update-checksums
COPY . /demo-app/
RUN rm -rf node_modules
RUN yarn && ng build

# Stage - Production
FROM nginx:1.17-alpine
COPY --from=build /demo-app/dist/v4-prototype /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]